"""
Django settings for NewsStudyRostelecom project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
from pathlib import Path
import os
import environ
env = environ.Env()
#environ.Env.read_env()
env.read_env()
#proba

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # От дид
#print('дидж')
#print(BASE_DIR)
BASE_DIR = Path(__file__).resolve().parent.parent
print('наш')
print(BASE_DIR)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-)1jvbggbr5)ou6&!8^hnlh_a!52asw5ymve_@h+g&8g(it%6+s'
SECRET_KEY = env("SECRET_KEY")
#print(SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True
DEBUG = False
## --insecure

# ALLOWED_HOSTS = ['*','178.69.64.68:8000','178.69.64.68','127.0.0.1','127.0.0.1:8000','192.168.0.30','192.168.0.30:8000']
#ALLOWED_HOSTS = ['178.69.64.68:8000','178.69.64.68:8001', '178.69.64.68', '127.0.0.1', '127.0.0.1:8000', '192.168.0.30', '192.168.0.2', '192.168.0.30:8000', '192.168.0.2:8001']
ALLOWED_HOSTS = ['178.69.64.68','178.69.64.68', 'help35.ru', 'www.help35.ru', '127.0.0.1', '192.168.0.30', '192.168.0.2']


# Application definition




INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap5',
    'main',
    'news',
    'users',
    'debug_toolbar',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_extensions',  # pip install django-extensions
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

INTERNAL_IPS = ['127.0.0.1',]

ROOT_URLCONF = 'NewsStudyRostelecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsStudyRostelecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = { 'default':
#               { 'ENGINE': 'django.db.backends.postgresql_psycopg2',
#                 'NAME': 'django',
#                 'USER': 'alexzav_pg',
#                 'PASSWORD': 'president',
#                 'HOST': '192.168.0.2',
#                 'PORT': '5432'
#                 }
#               }

DATABASES = { 'default':
              { 'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': env("DB_NAME"),
                'USER': env('DB_USER'),
                'PASSWORD': env('DB_PASSWORD'),
                'HOST': env('DB_HOST'),
                'PORT': env('DB_PORT')
                }
              }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'
#LANGUAGE_CODE = 'en-en'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    "news/static",
    "main/static",
    "users/static",
]

#print(BASE_DIR)
#print(os.path.dirname(BASE_DIR))

#STATIC_ROOT=os.path.join(os.path.dirname(BASE_DIR), STATIC_URL)
#STATIC_ROOT=os.path.join(BASE_DIR, STATIC_URL)
print('базедир')
print(BASE_DIR)
print('статик рут')
#print(STATIC_ROOT)



MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
print('медиа рут')
#print(MEDIA_ROOT)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACK = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

#########
# можем тут указать переменную куда отправлять если требуется авторизация но если мы пропишем прямо в классах или декораторе для функций, то там будет важнее
##### LOGIN_URL = 'users:login'
#для функци делаем #@login_required(logi_url='users:login') пример от балды надо вообще на юсера олтправить
#
#для класса первым вставляем в класс и потом уже в классе ниже пишем logi_url='users:login' 70 где-то лекц
#LoginRequiredMixin  - импортировать
# пример
#class TagCreateView(LoginRequiredMixin,  CreateView):
#    login_url = 'users:login'
########

#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.mail.ru"
EMAIL_PORT = 465
EMAIL_HOST_USER = "test@piloramservis.ru"
EMAIL_HOST_PASSWORD = "zqx4E8s5bEek49uj87Jm"
EMAIL_USE_SSL = True

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER
